version: '3.8'

networks:
  default:
    name: 'teste-sqs'

services:
  api:
    build:
      context: .
      target: API
    image: api
    container_name: api
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
    command: npm start
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: postgres:15.4-alpine
    container_name: db
    environment:
      - POSTGRES_USER=testing
      - POSTGRES_PASSWORD=test123
    ports:
      - 5432:5432
    healthcheck:
      test:  "pg_isready -U testing"
      interval: 1s
      timeout: 5s
      retries: 5